"use client";
import { DesignCopy } from "@/components/design/runtime";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useViewId } from "./view-provider";
import type { Course, CourseMeeting, CourseOfficeHour } from "@/lib/mock-data";
const field="mt-1 w-full rounded-lg border border-stone-200 bg-white p-2 text-sm outline-none";
const button="rounded-lg border border-stone-200 bg-white px-3 py-2 text-xs hover:bg-stone-50 disabled:opacity-40";
const days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
export function CourseEditor({course}:{course:Course}) {
  const viewId=useViewId();const router=useRouter();
  const [open,setOpen]=useState(false);const [draft,setDraft]=useState(course);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [rebuild,setRebuild]=useState(false);
  const update=(patch:Partial<Course>)=>setDraft(current=>({...current,...patch}));
  const meeting=(index:number,patch:Partial<CourseMeeting>)=>update({meetings:(draft.meetings||[]).map((m,i)=>i===index?{...m,...patch}:m)});
  const office=(index:number,patch:Partial<CourseOfficeHour>)=>update({officeHours:(draft.officeHours||[]).map((m,i)=>i===index?{...m,...patch}:m)});
  const submit=async()=>{setBusy(true);setError("");try{const res=await fetch(`/api/${viewId}/courses/${encodeURIComponent(course.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,rebuildSchedule:rebuild})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not save course.");setOpen(false);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save.");}finally{setBusy(false);}};
  const remove=async()=>{if(!window.confirm(`Remove ${course.code}? Its artifacts, assignments, events and tasks will be kept under Unassigned.`))return;setBusy(true);setError("");try{const res=await fetch(`/api/${viewId}/courses/${encodeURIComponent(course.id)}`,{method:"DELETE"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not remove course.");router.push("/courses");router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Could not remove course.");setBusy(false);}};
  return <><button data-design-id="m-e0c9799867b7" className={button} disabled={course.id==="unassigned"} onClick={()=>{setDraft(course);setError("");setRebuild(false);setOpen(true);}}><DesignCopy id="m-e0c9799867b7">Edit course</DesignCopy></button>
    {open&&<div data-design-id="m-c8ef0249770a" className="fixed inset-0 z-[150] flex items-center justify-center bg-black/25 p-5" role="dialog" aria-modal="true" aria-label="Edit course"><form data-design-id="m-cca621679218" onSubmit={e=>{e.preventDefault();void submit();}} className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-xl">
      <header data-design-id="m-dcaa103e95b8" className="flex items-center justify-between border-b border-stone-100 p-5"><h2 data-design-id="m-286b3ef615b1" className="text-lg font-medium">Edit {course.code}</h2><button data-design-id="m-f71393fa87d0" type="button" disabled={busy} className={button} onClick={()=>setOpen(false)}><DesignCopy id="m-f71393fa87d0">Cancel</DesignCopy></button></header>
      <div data-design-id="m-24051fea8f39" className="space-y-6 overflow-y-auto p-6">
        <div data-design-id="m-e945c0385097" className="grid gap-4 sm:grid-cols-2">{(["code","title","instructor","term","instructorEmail","instructorOffice"] as const).map(key=><label data-design-id="m-04634a61438b" key={key} className="text-xs text-stone-500">{({code:"Course code",title:"Course title",instructor:"Instructor",term:"Term",instructorEmail:"Instructor email",instructorOffice:"Office"})[key]}<input data-design-id="m-54a7b42bb5f9" required={key==="code"||key==="title"} type={key==="instructorEmail"?"email":"text"} className={field} value={draft[key]||""} onChange={e=>update({[key]:e.target.value})}/></label>)}</div>
        <label data-design-id="m-7d9c946281ca" className="block text-xs text-stone-500">Description<textarea data-design-id="m-a0970fc5668b" className={field} rows={3} value={draft.description} onChange={e=>update({description:e.target.value})}/></label>
        <div data-design-id="m-5af99efaf9e4" className="grid gap-4 sm:grid-cols-2">{(["termStartsAt","termEndsAt"] as const).map(key=><label data-design-id="m-9c0574fbaf73" key={key} className="text-xs text-stone-500">{key==="termStartsAt"?"Term starts":"Term ends"}<input data-design-id="m-b83dbe9224a1" type="date" className={field} value={draft[key]?.slice(0,10)||""} onChange={e=>update({[key]:e.target.value})}/></label>)}</div>
        <section data-design-id="m-cc712f379e50" className="space-y-3"><h3 data-design-id="m-d72470084ff6" className="text-sm font-medium"><DesignCopy id="m-d72470084ff6">Weekly classes</DesignCopy></h3>{(draft.meetings||[]).map((m,i)=><div data-design-id="m-55e7eefb4d21" key={i} className="space-y-3 rounded-lg border border-stone-200 p-3">
          <div data-design-id="m-32a4108869cb" className="flex items-center gap-3"><select data-design-id="m-088486a0de16" aria-label="Meeting type" className={field} value={m.kind} onChange={e=>meeting(i,{kind:e.target.value as CourseMeeting["kind"]})}>{["lecture","lab","discussion","seminar"].map(kind=><option key={kind}>{kind}</option>)}</select><button data-design-id="m-b8c06c7fe4af" type="button" className="text-xs text-red-700" onClick={()=>update({meetings:draft.meetings?.filter((_,n)=>n!==i)})}><DesignCopy id="m-b8c06c7fe4af">Remove</DesignCopy></button></div>
          <div data-design-id="m-d8ad2be29276" className="flex flex-wrap gap-3">{days.map((day,n)=><label data-design-id="m-994f518b289a" data-design-key={day} key={day} className="flex gap-1 text-xs"><input data-design-id="m-93776d0a1be2" type="checkbox" checked={m.days.includes(n)} onChange={e=>meeting(i,{days:e.target.checked?[...m.days,n].sort():m.days.filter(d=>d!==n)})}/>{day}</label>)}</div>
          <div data-design-id="m-5381dbe65bf0" className="grid grid-cols-3 gap-3"><label data-design-id="m-9d346dee196a" className="text-xs text-stone-500">Start<input data-design-id="m-6ef31cdfa83c" type="time" required className={field} value={m.start} onChange={e=>meeting(i,{start:e.target.value})}/></label><label data-design-id="m-525bafa2fe63" className="text-xs text-stone-500">End<input data-design-id="m-00c55c4b098c" type="time" required className={field} value={m.end} onChange={e=>meeting(i,{end:e.target.value})}/></label><label data-design-id="m-90b39b2ee1bf" className="text-xs text-stone-500">Location<input data-design-id="m-0d6b70411d2c" className={field} value={m.location||""} onChange={e=>meeting(i,{location:e.target.value})}/></label></div>
        </div>)}<button data-design-id="m-ef30c62e7bb8" type="button" className={button} onClick={()=>update({meetings:[...draft.meetings||[],{kind:"lecture",days:[1],start:"09:00",end:"10:00",location:""}]})}><DesignCopy id="m-ef30c62e7bb8">+ Weekly class</DesignCopy></button></section>
        <section data-design-id="m-f40630d1067c" className="space-y-3"><h3 data-design-id="m-a1cb0398a081" className="text-sm font-medium"><DesignCopy id="m-a1cb0398a081">Office hours</DesignCopy></h3>{(draft.officeHours||[]).map((m,i)=><div data-design-id="m-1c587a005f25" key={i} className="space-y-3 rounded-lg border border-stone-200 p-3"><div data-design-id="m-e807e3b53d25" className="grid grid-cols-2 gap-3"><label data-design-id="m-42889bda194e" className="text-xs text-stone-500">Host<input data-design-id="m-8935b3901711" className={field} value={m.host} onChange={e=>office(i,{host:e.target.value})}/></label><label data-design-id="m-d8a14c38a89d" className="text-xs text-stone-500">Day<select data-design-id="m-116c6fa94c54" className={field} value={m.day} onChange={e=>office(i,{day:Number(e.target.value)})}>{days.map((d,n)=><option key={d} value={n}>{d}</option>)}</select></label></div><div data-design-id="m-f5e4986e65a5" className="grid grid-cols-3 gap-3"><label data-design-id="m-69c6050a6c51" className="text-xs text-stone-500">Start<input data-design-id="m-adc46928e3ea" type="time" required className={field} value={m.start} onChange={e=>office(i,{start:e.target.value})}/></label><label data-design-id="m-153718354c9a" className="text-xs text-stone-500">End<input data-design-id="m-17fa55b21df0" type="time" required className={field} value={m.end} onChange={e=>office(i,{end:e.target.value})}/></label><label data-design-id="m-ff60e43a9652" className="text-xs text-stone-500">Location<input data-design-id="m-4eb76132bb26" className={field} value={m.location||""} onChange={e=>office(i,{location:e.target.value})}/></label></div><button data-design-id="m-fca74e10b7f0" type="button" className="text-xs text-red-700" onClick={()=>update({officeHours:draft.officeHours?.filter((_,n)=>n!==i)})}><DesignCopy id="m-fca74e10b7f0">Remove office hour</DesignCopy></button></div>)}<button data-design-id="m-1ee85e860fa4" type="button" className={button} onClick={()=>update({officeHours:[...draft.officeHours||[],{host:draft.instructor,day:1,start:"11:00",end:"12:00",location:""}]})}><DesignCopy id="m-1ee85e860fa4">+ Office hour</DesignCopy></button></section>
        <label data-design-id="m-6a63d1216016" className="flex items-start gap-3 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-stone-600"><input data-design-id="m-4f289453849b" type="checkbox" checked={rebuild} onChange={e=>setRebuild(e.target.checked)}/><span data-design-id="m-ad5e2369a707"><DesignCopy id="m-ad5e2369a707">Rebuild this course’s weekly calendar from these term dates and times. This replaces imported class and office-hour occurrences, including individual edits and skipped dates. Manually added events and assignment deadlines stay.</DesignCopy></span></label>
        <section data-design-id="m-efb39665811f" className="space-y-3"><h3 data-design-id="m-3c7f85a0e723" className="text-sm font-medium"><DesignCopy id="m-3c7f85a0e723">Course policies</DesignCopy></h3>{(["ai","late","attendance","integrity"] as const).map(key=><label data-design-id="m-3512021441b3" key={key} className="block text-xs capitalize text-stone-500">{key==="ai"?"AI policy":key}<textarea data-design-id="m-06ebe6edb670" className={field} rows={2} value={draft.policies?.[key]||""} onChange={e=>update({policies:{...draft.policies,[key]:e.target.value}})}/></label>)}</section>
      </div><footer data-design-id="m-7c4568434013" className="flex items-center justify-between gap-4 border-t border-stone-100 p-5"><button data-design-id="m-26deb25c31b7" type="button" disabled={busy} className="text-xs text-red-700" onClick={()=>void remove()}><DesignCopy id="m-26deb25c31b7">Remove course</DesignCopy></button><p data-design-id="m-aefb3b32058f" role="alert" className="text-sm text-red-700">{error}</p><button data-design-id="m-761f019cd7da" disabled={busy} className="shrink-0 rounded-lg bg-stone-900 px-5 py-2 text-sm text-white disabled:opacity-40">{busy?"Saving…":"Save course"}</button></footer>
    </form></div>}
  </>;
}
