"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useViewId } from "./view-provider";
import type { Course, CourseMeeting, CourseOfficeHour } from "@/lib/mock-data";
const field="mt-1 w-full rounded-lg border border-stone-200 bg-white p-2 text-sm outline-none";
const button="rounded-lg border border-stone-200 bg-white px-3 py-2 text-xs hover:bg-stone-50 disabled:opacity-40";
const days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
export function CourseEditor({course}:{course:Course}) {
  const viewId=useViewId();const router=useRouter();
  const [open,setOpen]=useState(false);const [draft,setDraft]=useState(course);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [rebuild,setRebuild]=useState(false);
  const update=(patch:Partial<Course>)=>setDraft(current=>({...current,...patch}));
  const meeting=(index:number,patch:Partial<CourseMeeting>)=>update({meetings:(draft.meetings||[]).map((m,i)=>i===index?{...m,...patch}:m)});
  const office=(index:number,patch:Partial<CourseOfficeHour>)=>update({officeHours:(draft.officeHours||[]).map((m,i)=>i===index?{...m,...patch}:m)});
  const submit=async()=>{setBusy(true);setError("");try{const res=await fetch(`/api/${viewId}/courses/${encodeURIComponent(course.id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,rebuildSchedule:rebuild})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not save course.");setOpen(false);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save.");}finally{setBusy(false);}};
  const remove=async()=>{if(!window.confirm(`Remove ${course.code}? Its artifacts, assignments, events and tasks will be kept under Unassigned.`))return;setBusy(true);setError("");try{const res=await fetch(`/api/${viewId}/courses/${encodeURIComponent(course.id)}`,{method:"DELETE"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not remove course.");router.push("/courses");router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Could not remove course.");setBusy(false);}};
  return <><button className={button} disabled={course.id==="unassigned"} onClick={()=>{setDraft(course);setError("");setRebuild(false);setOpen(true);}}>Edit course</button>
    {open&&<div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/25 p-5" role="dialog" aria-modal="true" aria-label="Edit course"><form onSubmit={e=>{e.preventDefault();void submit();}} className="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-white shadow-xl">
      <header className="flex items-center justify-between border-b border-stone-100 p-5"><h2 className="text-lg font-medium">Edit {course.code}</h2><button type="button" disabled={busy} className={button} onClick={()=>setOpen(false)}>Cancel</button></header>
      <div className="space-y-6 overflow-y-auto p-6">
        <div className="grid gap-4 sm:grid-cols-2">{(["code","title","instructor","term","instructorEmail","instructorOffice"] as const).map(key=><label key={key} className="text-xs text-stone-500">{({code:"Course code",title:"Course title",instructor:"Instructor",term:"Term",instructorEmail:"Instructor email",instructorOffice:"Office"})[key]}<input required={key==="code"||key==="title"} type={key==="instructorEmail"?"email":"text"} className={field} value={draft[key]||""} onChange={e=>update({[key]:e.target.value})}/></label>)}</div>
        <label className="block text-xs text-stone-500">Description<textarea className={field} rows={3} value={draft.description} onChange={e=>update({description:e.target.value})}/></label>
        <div className="grid gap-4 sm:grid-cols-2">{(["termStartsAt","termEndsAt"] as const).map(key=><label key={key} className="text-xs text-stone-500">{key==="termStartsAt"?"Term starts":"Term ends"}<input type="date" className={field} value={draft[key]?.slice(0,10)||""} onChange={e=>update({[key]:e.target.value})}/></label>)}</div>
        <section className="space-y-3"><h3 className="text-sm font-medium">Weekly classes</h3>{(draft.meetings||[]).map((m,i)=><div key={i} className="space-y-3 rounded-lg border border-stone-200 p-3">
          <div className="flex items-center gap-3"><select aria-label="Meeting type" className={field} value={m.kind} onChange={e=>meeting(i,{kind:e.target.value as CourseMeeting["kind"]})}>{["lecture","lab","discussion","seminar"].map(kind=><option key={kind}>{kind}</option>)}</select><button type="button" className="text-xs text-red-700" onClick={()=>update({meetings:draft.meetings?.filter((_,n)=>n!==i)})}>Remove</button></div>
          <div className="flex flex-wrap gap-3">{days.map((day,n)=><label key={day} className="flex gap-1 text-xs"><input type="checkbox" checked={m.days.includes(n)} onChange={e=>meeting(i,{days:e.target.checked?[...m.days,n].sort():m.days.filter(d=>d!==n)})}/>{day}</label>)}</div>
          <div className="grid grid-cols-3 gap-3"><label className="text-xs text-stone-500">Start<input type="time" required className={field} value={m.start} onChange={e=>meeting(i,{start:e.target.value})}/></label><label className="text-xs text-stone-500">End<input type="time" required className={field} value={m.end} onChange={e=>meeting(i,{end:e.target.value})}/></label><label className="text-xs text-stone-500">Location<input className={field} value={m.location||""} onChange={e=>meeting(i,{location:e.target.value})}/></label></div>
        </div>)}<button type="button" className={button} onClick={()=>update({meetings:[...draft.meetings||[],{kind:"lecture",days:[1],start:"09:00",end:"10:00",location:""}]})}>+ Weekly class</button></section>
        <section className="space-y-3"><h3 className="text-sm font-medium">Office hours</h3>{(draft.officeHours||[]).map((m,i)=><div key={i} className="space-y-3 rounded-lg border border-stone-200 p-3"><div className="grid grid-cols-2 gap-3"><label className="text-xs text-stone-500">Host<input className={field} value={m.host} onChange={e=>office(i,{host:e.target.value})}/></label><label className="text-xs text-stone-500">Day<select className={field} value={m.day} onChange={e=>office(i,{day:Number(e.target.value)})}>{days.map((d,n)=><option key={d} value={n}>{d}</option>)}</select></label></div><div className="grid grid-cols-3 gap-3"><label className="text-xs text-stone-500">Start<input type="time" required className={field} value={m.start} onChange={e=>office(i,{start:e.target.value})}/></label><label className="text-xs text-stone-500">End<input type="time" required className={field} value={m.end} onChange={e=>office(i,{end:e.target.value})}/></label><label className="text-xs text-stone-500">Location<input className={field} value={m.location||""} onChange={e=>office(i,{location:e.target.value})}/></label></div><button type="button" className="text-xs text-red-700" onClick={()=>update({officeHours:draft.officeHours?.filter((_,n)=>n!==i)})}>Remove office hour</button></div>)}<button type="button" className={button} onClick={()=>update({officeHours:[...draft.officeHours||[],{host:draft.instructor,day:1,start:"11:00",end:"12:00",location:""}]})}>+ Office hour</button></section>
        <label className="flex items-start gap-3 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-stone-600"><input type="checkbox" checked={rebuild} onChange={e=>setRebuild(e.target.checked)}/><span>Rebuild this course’s weekly calendar from these term dates and times. This replaces imported class and office-hour occurrences, including individual edits and skipped dates. Manually added events and assignment deadlines stay.</span></label>
        <section className="space-y-3"><h3 className="text-sm font-medium">Course policies</h3>{(["ai","late","attendance","integrity"] as const).map(key=><label key={key} className="block text-xs capitalize text-stone-500">{key==="ai"?"AI policy":key}<textarea className={field} rows={2} value={draft.policies?.[key]||""} onChange={e=>update({policies:{...draft.policies,[key]:e.target.value}})}/></label>)}</section>
      </div><footer className="flex items-center justify-between gap-4 border-t border-stone-100 p-5"><button type="button" disabled={busy} className="text-xs text-red-700" onClick={()=>void remove()}>Remove course</button><p role="alert" className="text-sm text-red-700">{error}</p><button disabled={busy} className="shrink-0 rounded-lg bg-stone-900 px-5 py-2 text-sm text-white disabled:opacity-40">{busy?"Saving…":"Save course"}</button></footer>
    </form></div>}
  </>;
}
