import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
async function main() {
  process.env.MONARCH_DATA_ROOT = await mkdtemp(path.join(tmpdir(),"monarch-academic-check-"));
  const db = await import("../src/lib/local-db");
  const academic = await import("../src/lib/academic-store");
  const {writeWorkspaceCollections} = await import("../src/lib/workspace-store");
  const course = await db.createCourse("test-one",{code:"BIO 100",title:"Biology"});
  const assignment = await academic.saveAssignment("test-one",null,{title:"Cell response",type:"paper",courseSlug:course.slug,dueAt:"2026-09-25T17:00"});
  let store = await db.readViewStore("test-one");
  assert.equal(store.calendar.filter(e=>e.assignmentId===assignment.id).length,1);
  const eventId=store.calendar.find(e=>e.assignmentId===assignment.id)!.id;
  await writeWorkspaceCollections("test-one",store,{planner:[{id:"task1",key:"TASK-1",title:"Draft response",status:"todo",courseId:course.id,assignmentId:assignment.id,children:[{id:"task2",key:"TASK-2",title:"Find evidence",status:"todo",assignmentId:assignment.id}]}]});
  await academic.saveAssignment("test-one",assignment.id,{dueAt:"2026-09-27T20:00",title:"Revised response"});
  store=await db.readViewStore("test-one");
  assert.equal(store.calendar.find(e=>e.id===eventId)?.startsAt,"2026-09-27T20:00");
  assert.equal(store.planner[0].dueAt,"2026-09-27T20:00");
  assert.equal(store.planner[0].children?.[0].dueAt,"2026-09-27T20:00");
  await academic.saveCalendarEvent("test-one",eventId,{startsAt:"2026-09-28T21:00",endsAt:"2026-09-28T21:00"});
  store=await db.readViewStore("test-one");
  assert.equal(store.assignments[0].dueAt,"2026-09-28T21:00");
  assert.equal(store.planner[0].children?.[0].dueAt,"2026-09-28T21:00");
  await academic.saveCalendarEvent("test-one",eventId,{tagIds:["project"]});
  await academic.saveAssignment("test-one",assignment.id,{title:"Retitled paper"});
  assert.deepEqual((await db.readViewStore("test-one")).calendar.find(e=>e.id===eventId)?.tagIds,["project"]);
  await academic.saveCalendarEvent("test-one",eventId,{tagIds:[]});
  await academic.saveAssignment("test-one",assignment.id,{title:"Revised response"});
  assert.deepEqual((await db.readViewStore("test-one")).calendar.find(e=>e.id===eventId)?.tagIds,[]);
  const untagged=await db.createPlannerIssue("test-one",{title:"Explicitly no tags",label:"Exam",tagIds:[]});
  assert.deepEqual((await db.getPlannerIssue("test-one",untagged.key))?.tagIds,[]);
  await db.deletePlannerIssue("test-one",untagged.key);
  console.log("PASS: visual tags persist independently of deadlines and explicit empty tags stay cleared");
  await assert.rejects(academic.saveAssignment("test-one",assignment.id,{dueAt:"2026-02-30"}),/does not exist/);
  await assert.rejects(academic.saveCalendarEvent("test-one",eventId,{startsAt:"2026-09-29T25:00"}),/does not exist/);
  await assert.rejects(academic.deleteCalendarEvent("test-one",eventId),/assignment deadline/);
  console.log("PASS: assignment ↔ calendar deadline synchronization, nested task propagation and invalid date rejection");
  const manual=await academic.saveCalendarEvent("test-one",null,{title:"Study group",courseId:course.id,startsAt:"2026-09-21T18:00",endsAt:"2026-09-21T19:00",kind:"session"});
  const patch={termStartsAt:"2026-09-21",termEndsAt:"2026-10-02",meetings:[{kind:"lecture",days:[1,3],start:"09:00",end:"10:00"}],officeHours:[{host:"Professor",day:2,start:"11:00",end:"12:00"}],rebuildSchedule:true};
  await academic.updateCourse("test-one",course.id,patch);
  store=await db.readViewStore("test-one");
  const generated=store.calendar.filter(e=>e.generatedBy==="syllabus");
  assert.equal(generated.length,6);
  await academic.updateCourse("test-one",course.id,{...patch,code:"BIO 101"});
  store=await db.readViewStore("test-one");
  assert.deepEqual(store.calendar.filter(e=>e.generatedBy==="syllabus").map(e=>e.id).sort(),generated.map(e=>e.id).sort());
  assert.ok(store.calendar.some(e=>e.id===manual.id));
  assert.ok(store.calendar.some(e=>e.id===eventId));
  assert.equal(store.planner[0].course,"BIO 101");
  await academic.deleteAssignment("test-one",assignment.id);
  store=await db.readViewStore("test-one");
  assert.equal(store.assignments.length,0);assert.ok(!store.calendar.some(e=>e.id===eventId));
  assert.equal(store.planner[0].title,"Draft response");assert.equal(store.planner[0].assignmentId,undefined);
  console.log("PASS: weekly schedule rebuild retains event identities and manual events; assignment deletion preserves tasks");
  const artifact=await db.createArtifact("test-one",{title:"Keep my notes",kind:"notes",courseId:course.id});
  const remainingAssignment=await academic.saveAssignment("test-one",null,{title:"Keep my assignment",courseSlug:course.slug,dueAt:"2026-10-01"});
  await academic.deleteCourse("test-one",course.id);
  store=await db.readViewStore("test-one");
  assert.equal(store.artifacts.find(a=>a.id===artifact.id)?.courseId,"unassigned");
  assert.equal(store.assignments.find(a=>a.id===remainingAssignment.id)?.courseSlug,"unassigned");
  assert.equal(store.calendar.find(e=>e.id===manual.id)?.courseId,"unassigned");
  assert.equal(store.planner[0].courseId,"unassigned");
  await assert.rejects(academic.deleteCourse("test-one","unassigned"),/cannot be deleted/);
  console.log("PASS: removing a course moves schoolwork to Unassigned without deleting it");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
